version: 2.1
orbs:
  docker: circleci/docker@1.3.0
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: rp-frontend/web
          tag: latest
          registry: registry.heroku.com
