version: 2.1
orbs:
  docker: circleci/docker@1.3.0
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: registry.heroku.com/rp-frontend/web
          tag: 'latest'
          auth:
            username: $HEROKU_EMAIL
            password: $HEROKU_APIKEY
